name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: chainloop-ui

      - name: Build React
        run: npm run build
        working-directory: chainloop-ui
        env:
            VITE_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            VITE_API_URL: https://purevitadrinks.com/api

      - name: Upload Build
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 21
          local-dir: chainloop-ui/dist/
          server-dir: build/
          exclude: |
            **/.git*
            **/node_modules/**
            **/vendor/**